# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets:
        list:
            quality: 85
            filters:
                thumbnail: { size: [700, 600], mode: outbound }
        view:
            quality: 85
            filters:
                thumbnail: { size: [950, 800], mode: outbound }
        edit_other:
            quality: 85
            filters:
                thumbnail: { size: [ 300, 300 ], mode: outbound }
        creator_list:
            quality: 85
            filters:
                thumbnail: { size: [ 200, 200 ], mode: outbound }