# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets:
        list:
            quality: 85
            filters:
                thumbnail: { size: [100, 100], mode: outbound }
        view:
            quality: 85
            filters:
                thumbnail: { size: [300, 200], mode: outbound }